name: WormholeXTreme
main: de.luricos.bukkit.WormholeXTreme.Wormhole.WormholeXTreme
version: 1.1.6
api-version: 1.21
authors: [Lologarithm, alron, lycano, Dakto_]
softdepend: [PermissionsEx, WormholeXTremeWorlds, Help]
description: Wormhole X-Treme! Wormholes as travel portals. Splash Effect, IDC, Iris, configurable Wormhole materials, and much much more.
commands:
  dial:
    description: Dial a remote Stargate.
    usage: /<command> <StarGate> [IDC]
  wormhole:
    description: Wormhole administration and configuration commands.
    aliases: [wxt]
    usage: /<command> <subcommand>
  wxlist:
    description: List stargates.
    usage: /<command> [all|self]
  wxtop:
    description: Show most visited stargates leaderboard.
    usage: /<command> [count]
  wxbuild:
    description: Automatically Build Stargate.
    usage: /<command> <GateShape>
  wxbuildlist:
    description: List available gate shapes.
    usage: /<command>
  wxremove:
    description: Remove a stargate, optionally destroy its blocks.
    usage: /<command> <GateName> [-all]
  wxcompass:
    description: Point compass needle at nearest Stargate.
    usage: /<command>
  wxcomplete:
    description: Complete StarGate construction.
    usage: /<command> <GateName> idc=[IDC] net=[Net]
  wxidc:
    description: Gets or sets a gates IDC code.
    usage: /<command> <GateName> <optional_set_idc>
  wxforce:
    description: Forcefully shut down, darken, and open the iris of a gate.
    usage: /<command> <gateName|-all>
  wxgo:
    description: Teleport to specified wormhole.
    usage: /<command> <GateName>
  wxreload:
    description: Reload WormholeXTreme.
    aliases: [wxre]
    usage: /<command> [now]
  wxstatus:
    description: Show system status.
    aliases: [wxs]
    usage: /<command> [all]
  wxconvertdb:
    description: Convert a NovyXtreme stargatesList.json database into the WormholeXTreme database.
    usage: /<command>
permissions:
  wormhole.use.sign:
    description: Player is able to use the dialer sign
    default: true
  wormhole.use.dialer:
    description: Player is able to use the dialer
    default: true
  wormhole.use.compass:
    description: Can use the wormhole compass
    default: true
  wormhole.use.*:
    description: Can use all wormhole use nodes
    children:
      wormhole.use.sign: true
      wormhole.use.dialer: true
      wormhole.use.compass: true
  wormhole.cooldown.groupone:
    description: Use cooldown group one
    default: false
  wormhole.cooldown.grouptwo:
    description: Use cooldown group two
    default: false
  wormhole.cooldown.groupthree:
    description: Use cooldown group three
    default: false
  wormhole.cooldown.*:
    description: Can use all cooldown nodes
    children:
      wormhole.cooldown.groupone: true
      wormhole.cooldown.grouptwo: true
      wormhole.cooldown.groupthree: true
  wormhole.remove.own:
    description: Can remove own gates
    default: op
  wormhole.remove.all:
    description: Can remove a gate using -all command
    default: op
  wormhole.remove.*:
    description: Can use all remove permissions
    children:
      wormhole.remove.own: true
      wormhole.remove.all: true
  wormhole.build:
    description: Can build Wormhole
    default: op
  wormhole.build.all:
    description: Can build Wormhole on any network, bypassing network.build restrictions
    default: op
  wormhole.build.groupone:
    description: Build restriction for groupone
    default: false
  wormhole.build.grouptwo:
    description: Build restriction for grouptwo
    default: false
  wormhole.build.groupthree:
    description: Build restriction for groupthree
    default: false
  wormhole.build.*:
    description: Can use all build permissions
    children:
      wormhole.build: true
      wormhole.build.all: true
      wormhole.build.groupone: true
      wormhole.build.grouptwo: true
      wormhole.build.groupthree: true
  wormhole.config:
    description: Can modify Wormhole config
    default: op
  wormhole.list:
    description: Can list wormhole gates
    default: op
  wormhole.list.all:
    description: Can list all wormhole gates with /wxlist all
    default: op
  wormhole.list.self:
    description: Can list own wormhole gates with /wxlist self
    default: true
  wormhole.top:
    description: Can view the most visited stargates leaderboard with /wxtop
    default: true
  wormhole.network.use:
    description: Can use gate network
    default: true
  wormhole.network.build:
    description: Can build networks
    default: op
  wormhole.network.*:
    description: Can use all network permissions
    children:
      wormhole.network.use: true
      wormhole.network.build: true
  wormhole.go:
    description: Can teleport to a wormhole location
    default: op
  wormhole.simple.use:
    description: Can use wormhole
    default: true
  wormhole.simple.config:
    description: Can modify configuration
    default: op
  wormhole.simple.build:
    description: Can build a wormhole
    default: op
  wormhole.simple.remove:
    description: Can remove a wormhole
    default: op
  wormhole.simple.*:
    description: Can use all simple wormhole nodes
    children:
      wormhole.simple.config: true
      wormhole.simple.build: true
      wormhole.simple.remove: true
      wormhole.simple.use: true
